FROM nginx:alpine

WORKDIR /client

# Copies html and js to the correct nginx folder
COPY . /usr/share/nginx/html
# Copies nginx configuration to container
COPY nginx.conf /etc/nginx/conf.d/default.conf

ENV PORT=80

# Exposes port 80
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]