---
apiVersion: v1
kind: Service
metadata:
  name: app2048-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
      app: app2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2048-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2048
  template:
    metadata:
      labels:
        app: app2048
    spec:
      containers:
      - name: app2048
        image: elpelado619/app2048:latest
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-cluster
                key: redis-password
          - name: REDIS_CLUSTER
            value: "redis-cluster"
        ports:
        - containerPort: 5000
